# Generated by Django 5.0.1 on 2024-03-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emaktabuz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogSenderBot',
        ),
    ]
