# Generated by Django 5.0.1 on 2024-03-03 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaktabuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 3, 3, 11, 9, 9, 179728, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
