# Generated by Django 5.0.2 on 2024-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaktabuz', '0002_alter_userdata_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=200)),
                ('bot_token', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
