# Generated by Django 5.0.2 on 2024-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzummarket', '0009_alter_product_rasmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rasmi2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
