# Generated by Django 5.0.2 on 2024-04-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzummarket', '0010_product_rasmi2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rasmi2',
        ),
    ]
