# Generated by Django 5.0.1 on 2024-03-02 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSenderBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('channel_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BackupBot',
                'verbose_name_plural': 'BackupBot',
            },
        ),
        migrations.CreateModel(
            name='Chat_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('model_type', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome_message', models.TextField()),
                ('prompt_start', models.TextField(blank=True, null=True)),
                ('parse_mode', models.CharField(blank=True, default='html', max_length=200, null=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ChatMode',
                'verbose_name_plural': 'ChatMode',
                'db_table': 'chat_mode',
            },
        ),
        migrations.CreateModel(
            name='ChatGptTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GPTToken',
                'verbose_name_plural': 'GPTToken',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_base', models.CharField(blank=True, max_length=200, null=True)),
                ('new_dialog_timeout', models.IntegerField(blank=True, default=600, null=True)),
                ('return_n_generated_images', models.IntegerField(default=1)),
                ('n_chat_modes_per_page', models.IntegerField(default=5)),
                ('image_size', models.CharField(default='512x512', max_length=200)),
                ('enable_message_streaming', models.BooleanField(default=True)),
                ('chatgpt_price_per_1000_tokens', models.FloatField(default=0.006)),
                ('gpt_price_per_1000_tokens', models.FloatField(default=0.002)),
                ('whisper_price_per_1_min', models.FloatField(default=0.006)),
                ('extra_field', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
            },
        ),
        migrations.CreateModel(
            name='GptModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, unique=True)),
                ('config', models.JSONField()),
            ],
            options={
                'verbose_name': 'GptModel',
                'verbose_name_plural': 'GptModel',
                'db_table': 'gpt_models',
            },
        ),
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('n_tokens', models.IntegerField()),
                ('n_images', models.IntegerField()),
                ('n_tts', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Subscribtion',
                'verbose_name_plural': 'Subscribtion',
                'db_table': 'subscribtion',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_token', models.CharField(max_length=255, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TelegramBot',
                'verbose_name_plural': 'TelegramBot',
            },
        ),
        migrations.CreateModel(
            name='TokenPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('n_tokens', models.IntegerField()),
                ('n_images', models.IntegerField()),
                ('n_tts', models.IntegerField()),
            ],
            options={
                'verbose_name': 'TokenPackage',
                'verbose_name_plural': 'TokenPackage',
                'db_table': 'token_package',
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('end', models.BooleanField(default=False)),
                ('chat_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatgpt_bot.chat_mode')),
                ('gpt_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatgpt_bot.gptmodels')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatgpt_bot.telegrambot')),
            ],
            options={
                'verbose_name': 'Dialog',
                'verbose_name_plural': 'Dialog',
                'db_table': 'dialog',
            },
        ),
        migrations.CreateModel(
            name='Messages_dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, null=True)),
                ('bot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_token', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('end', models.BooleanField(default=False)),
                ('dialog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_dialog', to='chatgpt_bot.dialog')),
            ],
            options={
                'verbose_name': 'MessagesDialog',
                'verbose_name_plural': 'MessagesDialog',
                'db_table': 'messages_dialog',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('en', 'English'), ('ru', 'Russian'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='uz', max_length=255, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, null=True)),
                ('n_used_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('n_generated_images', models.IntegerField(blank=True, default=0, null=True)),
                ('n_transcribed_seconds', models.IntegerField(blank=True, default=0, null=True)),
                ('user_allowed', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_choice', models.CharField(choices=[('uz', 'Uzbek'), ('en', 'English'), ('ru', 'Russian'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='uz', max_length=255, null=True)),
                ('daily_limit', models.IntegerField(blank=True, default=10, null=True)),
                ('extra_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('bot', models.ManyToManyField(to='chatgpt_bot.telegrambot')),
                ('current_chat_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_chat_mode', to='chatgpt_bot.chat_mode')),
                ('current_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatgpt_bot.gptmodels')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.AddField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatgpt_bot.telegramprofile', verbose_name='ChatGpt User'),
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Text Model',
                'verbose_name_plural': 'Text Models',
                'db_table': 'text_model',
                'unique_together': {('name', 'key')},
            },
        ),
    ]
