# Generated by Django 5.0.1 on 2024-03-01 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_bot', '0002_alter_telegrambot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatgpt_bot.telegramprofile', verbose_name='ChatGpt User'),
        ),
    ]
