# Generated by Django 5.0.1 on 2024-03-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_sign', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_token', models.CharField(max_length=255, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TelegramBot',
                'verbose_name_plural': 'TelegramBot',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caption_editor_bot.channel')),
            ],
            options={
                'unique_together': {('text', 'channel')},
            },
        ),
    ]
