# Generated by Django 5.0.2 on 2024-03-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDbBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BackupDb',
                'verbose_name_plural': 'BackupDb',
            },
        ),
    ]
